### PR TITLE
Add scale_down policy

### PR DESCRIPTION
**Pull request by jmalvarezf**
Hello,

I've modified a bit the script to try and adapt it to run in a Docker container. I've added arguments to the script instead of using the standard input, added user and password as an option (not mandatory) and added some parameters to make this script work similarly to the way marathon-lb-autoscale works.
Hope you find it useful.

Thanks!

### CODE REVIEW

**Comment by tkrausjr** [comment]
This is awesome.  I just reviewed it quickly have you tested it ?

**Comment by jmalvarezf** [comment]
Yes, we tested it with DC/OS 1.8.7 community edition and it is working as I expected. But you may want to test other things. I just wanted to share this with you to try and improve the functionality.

Thanks!

**Comment by kikicarbonell** [comment]
Any updates?

**Comment by tkrausjr** [comment]
@jmalvarezf Testing your branch now should merge it shortly sorry for delay.

**Pull request merged**
