### PR TITLE
Upgraded the Marathon Autoscaler

### PR DESCRIPTION
**Pull request by keith-mcclellan**
Julian and I have been working on enhancements to the utilization autoscaler to enable folks to:

a) run it in a cluster where security is enabled (both as a user and a service account)
b) run it under marathon management
c) Run in various scaling modes (CPU & Mem, CPU or Mem, CPU only, Memory only)
d) Set a target range for both CPU and Memory (min and max thresholds) 
e) Make it easy to run in a multi-tenant environment

### CODE REVIEW

**Comment by justinrlee** [comment]
Documentation comments:

`AS_MAX_CPU_TIME` and `AS_MIN_CPU_TIME` behave based on percentage of core CPU time (e.g., 80 is '80 percent of a single core').  They do not appear to be based on allocation.  I actually prefer the current behavior, I just think it could be documented better.  Although it may be worthwhile to change it from a '80' to a 0.80' to indicate 'number of cores in use'.

It's also inconsistent with memory behavior, because it looks like it results in memory thresholds being a percentage of allocation while CPU threshold is a raw number of cores.

One thing to be careful of is the fact that DC/OS (or Mesos) automatically increases your memory allocation by 32MB.  If you allocate 8 MB in the UI, Mesos will give you 40MB, and it appears that's the number used for the percentage calculation.

**Comment by justinrlee** [comment]
I don't think any of the above necessarily need to be addressed in this PR, just suggestions for the future.  I'm happy to merge now.

**Comment by justinrlee** [comment]
Also, for the future, it might be worth creating an option to scale up/down by a number of instances rather than a multiplier.

**Comment by justinrlee** [comment]
I'd suggest additional logging (for example, indicate what the actual threshold is: `Current average CPU time for app X = 100, threshold is 80`).  Also, when scaling, `Autoscale triggered based on (actual reason), changing instances from X to Y based on scale factor of Z`).

**Comment by justinrlee** [comment]
Might be worth adding documentation for `create-service-account.sh`.  Just a simple usage comment that you need to specify two parameters (`create-service-account.sh <service-account-name> <namespace-path>`)

**Comment by justinrlee** [comment]
You should probably document the `AS_AUTOSCALE_MULTIPLIER`.

**Comment by justinrlee** [comment]
The `create-service-account.sh` script didn't fully work for me (it didn't set up the permissions on the user account for me).  I just added `dcos:superuser full` to my service account.

**Comment by justinrlee** [comment]
I'd suggest changing `AS_TRIGGER_NUMBER` to `AS_HEAT_UP_FACTOR` (or something similarly related to `AS_COOL_DOWN_FACTOR`) - it's not intuitive that the two are scale up / scale down.

**Comment by justinrlee** [comment]
Scale up and scale down have slightly different behaviors - not a huge issue, just something to be fixed later.  Specifically, setting `AS_TRIGGER_NUMBER` to 3 means on the third out-of-compliance poll, it will trigger the scale up.  Setting `AS_COOL_DOWN_FACTOR` to 3 means it will wait for N+1 polls (4 polls) before scaling down.

**Comment by cs94njw** [comment]
I agree with @justinrlee - "You should probably document the AS_AUTOSCALE_MULTIPLIER".
I wanted autoscale to downscale my app from 2 to 1.
It said it was going to do it.
It counted the cool-down triggers.
Then when it wanted to scale-down, it said:

`2018-01-24 10:47:46,505 - marathon-autoscaler - DEBUG - scale_app: app_instances 2 target_instances 2`

Ah, this is because 2 / 1.5 = 1.3.  Math.ceil(1.3) = 2.  So you can't scale down from 2 to 1.

**Pull request merged**
